/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package io.github.prezi4j;

import com.apicatalog.jsonld.document.Document;
import com.apicatalog.jsonld.document.JsonDocument;

import java.io.InputStream;

public class Library {
    public boolean someLibraryMethod() {
        try {
            InputStream instr = this.getClass().getClassLoader().getResourceAsStream("full.json");
            Document document = JsonDocument.of(instr);
            System.out.println(document);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return true;
    }
}
